const ColorList = {
    'Entertainment':{
        icon:'popcorn',
        color:'coral'
    },
    'Travel':{
        icon:'train-car',
        color:'cornflowerblue'
    },
    'Food':{
        icon:'food',
        color:'orangered'
    },
    'Shopping':{
        icon:'shopping-outline',
        color:'chocolate'
    },
    'Health':{
        icon:'hospital-box-outline',
        color:'red'
    },
    'Sports':{
        icon:'cricket',
        color:'brown'
    },
    'Electronics':{
        icon:'cellphone-link',
        color:'midnightblue'
    },
    'Bills':{
        icon:'receipt',
        color:'lightslategrey'
    },
    'Others':{
        icon:'cash-check',
        color:'green'
    }
}

export default ColorList